const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Task = require("./models/task");
const { geocodeAddress } = require("./utils/geocode");

dotenv.config();

const rawInput = `KOPERASI DESA MERAH PUTIH CISONDARI KECAMATAN PASIRJAMBU 	 Jalan Raya Cisondari Nomor 19/1812 
 KOPERASI DESA MERAH PUTIH MEKARJAYA KECAMATAN BANJARAN 	 Jalan Cibaribis Nomor 112 
 KOPERASI DESA MERAH PUTIH LAMAJANG KECAMATAN PANGALENGAN 	 KAMPUNG KARANG TENGAH 
 KOPERASI DESA MERAH PUTIH BOJONGKUNCI KECAMATAN PAMEUNGPEUK 	 Jalan Tanjung Hilir Kampung Sukamanah 
 KOPERASI DESA MERAH PUTIH LEBAKWANGI KECAMATAN ARJASARI 	 Jalan Raya Arjasari Nomor 160 Kampung Pasirjati 
 KOPERASI DESA MERAH PUTIH GANDASARI KECAMATAN KATAPANG 	 JL GANDASARI NO.69 
 KOPERASI DESA MERAH PUTIH CIKONENG KECAMATAN CIPARAY 	 Kampung Cikoneng 
 KOPERASI DESA MERAH PUTIH CILUNCAT 	 JL. CILUNCAT NO 109 
 KOPERASI DESA MERAH PUTIH KUTAWARINGIN KECAMATAN KUTAWARINGIN 	 KP CIMAREME 
 KOPERASI DESA MERAH PUTIH BOJONGMALAKA KECAMATAN BALEENDAH KABUPATEN BANDUNG 	 Jalan Jatimekar Nomor 10 
 KOPERASI DESA MERAH PUTIH MARGAMUKTI KECAMATAN PANGALENGAN KABUPATEN BANDUNG 	 Kp. Sukamenak 
 KOPERASI DESA MERAH PUTIH DESA CIBIRUHILIR KECAMATAN CILEUNYI KABUPATEN BANDUNG 	 Pilar Biru Raya Nomor 1 
 KOPERASI DESA MERAH PUTIH KIANGROKE 	 Komplek Perkantoran Pemerintah Desa Kiangroke, Jalan Raya Pangalengan No.446 
 KOPERASI DESA MERAH PUTIH WANGISAGARA 	 Komplek Gedung Budaya, Kp. Pasir Garut 
 KOPERASI DESA MERAH PUTIH MARGAASIH KECEMATAN CICALENGKA 	 Kampung Cikarmajaya 
 KOPERASI DESA MERAH PUTIH MEKARSARI KECAMATAN CIMAUNG KABUPATEN BANDUNG 	 Kampung Mekarsari 
 KOPERASI DESA MERAH PUTIH PULOSARI KECAMATAN PANGALENGAN 	 Kp. Danosari 
 KOPERASI DESA MERAH PUTIH CIBODAS KECAMATAN KUTAWARINGIN 	 JL RAYA CIBODAS NO.100 KP. TIPAR 
 KOPERASI DESA MERAH PUTIH CINANGGELA KECAMATAN PACET KABUPATEN BANDUNG 	 Jalan Cinanggela No. 188 
 KOPERASI DESA MERAH PUTIH RANCAEKEK WETAN 	 JALAN RAYA RANCAEKEK-MAJALAYA NOMOR 97 
 KOPERASI DESA MERAH PUTIH LOA KECAMATAN PASEH 	 KAMPUNG LOA 
 KOPERASI DESA MERAH PUTIH BABAKAN KECAMATAN CIPARAY 	 Jalan Raya Rancakole KM. 6.3 Nomor 3 
 KOPERASI DESA MERAH PUTIH GIRIMULYA SATIA 	 Jalan Lembur Awi-Pasanggrahan No. 17 
 KOPERASI DESA MERAH PUTIH BANJARSARI KECAMATAN PANGALENGAN 	 JALAN PINTU MALABAR NOMOR 2 
 KOPERASI DESA MERAH PUTIH CIKONENG KECAMATAN PASIRJAMBU 	 KAMPUNG MUARA 
 KOPERASI DESA MERAH PUTIH JATISARI KECAMATAN KUTAWARINGIN 	 Jl. Cipedung 
 KOPERASI DESA MERAH PUTIH SARIMAHI 	 Jl. Budikarya No. 95 
 KOPERASI DESA MERAH PUTIH BOJONGMANGGU KECAMATAN PAMEUNGPEUK 	 Jalan Bojongmanggu Nomor 152 
 KOPERASI DESA MERAH PUTIH MAJALAYA KECAMATAN MAJALAYA 	 Jl. Stasion No. 22-24 Majalaya 
 KOPERASI DESA MERAH PUTIH SANTOSA KECAMATAN KERTASARI 	 KAMPUNG SANTOSA 
 KOPERASI DESA MERAH PUTIH TENJOLAYA KECAMATAN CICALENGKA 	 Jalan Kapten Sangun Nomor 61 
 KOPERASI DESA MERAH PUTIH CANGKUANG KECAMATAN CANGKUANG 	 Jalam Soreang - Banjaran No 170 
 KOPERASI DESA MERAH PUTIH TRIBAKTIMULYA KECAMATAN PANGALENGAN 	 JALAN KARYAWINATA NOMOR 5 KAMPUNG MEKARMUKTI 
 KOPERASI DESA MERAH PUTIH SRIRAHAYU KECAMATAN CIKANCUNG 	 Jalan Sawah Bera Nomor 01 
 KOPERASI DESA MERAH PUTIH NAGROG KECAMATAN CICALENGKA 	 JALAN RAYA TIMUR KM. 33 CICALENGKA 
 KOPERASI DESA MERAH PUTIH SOREANG KECAMATAN SOREANG 	 JL. RAYA SOREANG-BANJARAN NO. 334 KP. ANDIR 
 KOPERASI DESA MERAH PUTIH CIHAWUK KECAMATAN KERTASARI KABUPATEN BANDUNG 	 KAMPUNG PUNCAK MULYA 
 KOPERASI DESA MERAH PUTIH SANGKANHURIP KECAMATAN KATAPANG KABUPATEN BANDUNG 	 Kampung Junti Hilir 
 KOPERASI DESA MERAH PUTIH CICALENGKA KULON KECAMATAN CICALENGKA 	 JALAN RAYA BARAT NOMOR 279 CICALENGKA 
 KOPERASI DESA MERAH PUTIH CIPEDES KECAMATAN PASEH KABUPATEN BANDUNG 	 JALAN CIPEDES NOMOR 20 
 KOPERASI DESA MERAH PUTIH SUMBERSARI KECAMATAN CIPARAY KABUPATEN BANDUNG 	 Kampung Patrol 
 KOPERASI DESA MERAH PUTIH SADU KECAMATAN SOREANG 	 JL. RAYA SOREANG-CIWIDEY NO. 205 
 KOPERASI DESA MERAH PUTIH SUKAMAJU KECAMATAN CIMAUNG KABUPATEN BANDUNG 	 Kampung Madur 
 KOPERASI DESA MERAH PUTIH ALAMENDAH KECAMATAN RANCABALI 	 Jl RAYA CIWIDEY RANCABALI NO 05, KAMPUNG SINAPEUL 
 KOPERASI DESA MERAH PUTIH SUKAMANAH KECAMATAN PASEH 	 Kampung Sukamanah 
 KOPERASI DESA MERAH PUTIH NEGLAWANGI 	 JALAN KAWAH PAPANDAYAN NOMOR 2 
 KOPERASI DESA MERAH PUTIH CIKEMBANG KECAMATAN KERTASARI 	 KAMPUNG CIKEMBANG, JALAN RAYA CIKEMBANG NOMOR 60 
 KOPERASI DESA MERAH PUTIH DESA PANGGUH 	 JALAN BOJONG MUNCANG NOMOR 023 
 KOPERASI DESA MERAH PUTIH SINDANGSARI KECAMATAN PASEH 	 KAMPUNG SINGALOMBANG 
 KOPERASI DESA MERAH PUTIH NENGKELAN KECAMATAN CIWIDEY 	 Jl Surakerta No 1, Desa. Nengkelan , Kecamatan Ciwidey. Kabupaten Bandung 
 KOPERASI DESA MERAH PUTIH DESA GUNUNGLEUTIK KECAMATAN CIPARAY 	 JL.LIOSARI NO.122 
 KOPERASI DESA MERAH PUTIH PANYIRAPAN KECAMATAN SOREANG 	 KAMPUNG PANYIRAPAN 
 KOPERASI DESA MERAH PUTIH DESA MARGAMULYA KECAMATAN PASIRJAMBU 	 Kampung Margamulya 
 KOPERASI DESA MERAH PUTIH CIGENTUR KECAMATAN PASEH 	 Kampung Cibuah, Desa Cigentur, Kecamatan Paseh, Kabupaten Bandung 
 KOPERASI DESA MERAH PUTIH SUKARESMI KECAMATAN RANCABALI 	 KAMPUNG RANCAMULYA 
 KOPERASI DESA MERAH PUTIH MANGGUNGHARJA KECAMATAN CIPARAY KABUPATEN BANDUNG 	 Kampung Sukaharja 
 KOPERASI DESA MERAH PUTIH DESA TENJOLAYA KECAMATAN PASIRJAMBU KABUPATEN BANDUNG 	 Jl. Desa Tenjolaya No.1811 Kampung Babakan Liunggunung 
 KOPERASI DESA MERAH PUTIH PANUNDAAN KECAMATAN CIWIDEY 	 Jalan Raya Panundaan No.593 
 KOPERASI DESA MERAH PUTIH SUKAMANTRI KECAMATAN PASEH 	 Kampung Sukanegla 
 KOPERASI DESA MERAH PUTIH CIJAGRA KECAMATAN PASEH 	 Kampung Cijagra 
 KOPERASI DESA MERAH PUTIH DESA SUKAWENING KECAMATAN CIWIDEY 	 JL.CADAS BODAS NO.1 
 KOPERASI DESA MERAH PUTIH CILAMPENI KECAMATAN KATAPANG 	 Kantor Desa Cilampeni, Jalan Cilampeni Nomor 146 
 KOPERASI DESA MERAH PUTIH DESA SEKARWANGI KECAMATAN SOREANG 	 Jl. Terusan Kopo Km 15 No.436 
 KOPERASI DESA MERAH PUTIH SERANGMEKAR 	 Jl. Serangmekar - Sumbersari 
 KOPERASI DESA MERAH PUTIH SUKAPURA KECAMATAN KERTASARI KABUPATEN BANDUNG 	 Jalan Raya Pacet Km.17 Nomor 103 
 KOPERASI DESA MERAH PUTIH MEKARPAWITAN KECAMATAN PASEH 	 Kampung Baru 
 KOPERASI DESA MERAH PUTIH NAGRAK KECAMATAN CANGKUANG 	 JL PANYAUNGAN NO.146 
 KOPERASI DESA MERAH PUTIH CIPAKU KECAMATAN PASEH 	 KP. CIPAKU 
 KOPERASI DESA MERAH PUTIH DESA RESMI TINGAL KECAMATAN KERTASARI 	 KP. PECLUT 
 KOPERASI DESA MERAH PUTIH INDRAGIRI 	 Jalan Indragiri Nomor 9 
 KOPERASI DESA MERAH PUTIH TANGSIMEKAR 	 Kampung Tangsimekar 
 KOPERASI DESA MERAH PUTIH PANGALENGAN 	 KAMPUNG PASANGGRAHAN 
 KOPERASI DESA MERAH PUTIH WANASUKA KECAMATAN PANGALENGAN 	 JALAN WANASUKA, KAMPUNG WANASUKA 
 KOPERASI DESA MERAH PUTIH MARGALUYU KECAMATAN PANGALENGAN 	 Kampung Baru Mukti 
 KOPERASI DESA MERAH PUTIH RAWABOGO 	 Jalan Simpang Tiga Nomor 26 
 KOPERASI DESA MERAH PUTIH CIBEUREUM KECAMATAN KERTASARI 	 JALAN LAPANGSARI NOMOR 19 
 KOPERASI DESA MERAH PUTIH RANCAEKEK KULON 	 JALAN BABAKAN TETELAR NOMOR 82 
 KOPERASI DESA MERAH PUTIH JATISARI KECAMATAN CANGKUANG 	 KP NAGRAK 
 KOPERASI DESA MERAH PUTIH PANANJUNG KECAMATAN CANGKUANG 	 SUKAJADI NO 215 
 KOPERASI DESA MERAH PUTIH DESA SUDI 	 Dusun 2 Kp. Cisero 
 KOPERASI DESA MERAH PUTIH CIBODAS KECAMATAN PASIRJAMBU 	 Kampung Cibodas 
 KOPERASI DESA MERAH PUTIH TARUMAJAYA 	 Jalan Raya Pejaten-Situ Cisanti, Kampung Bongkor 
 KOPERASI DESA MERAH PUTIH TALUN KECAMATAN IBUN 	 Jalan Ciekek 
 KOPERASI DESA MERAH PUTIH MEKARSARI KECAMATAN PASIRJAMBU KABUPATEN BANDUNG 	 KAMPUNG GAMBUNG 
 KOPERASI DESA MERAH PUTIH PANYOCOKAN KECAMATAN CIWIDEY 	 Jalan Panyocokan KM 1 No. 15 
 KOPERASI DESA MERAH PUTIH CIKITU KECAMATAN PACET KABUPATEN BANDUNG 	 JALAN CIKITU PANGGILINGAN NO 01 
 KOPERASI DESA MERAH PUTIH SAGARACIPTA KECAMATAN CIPARAY KABUPATEN BANDUNG 	 Kampung Sanepa 
 KOPERASI DESA MERAH PUTIH KARAMAT MULYA KECAMATAN SOREANG 	 JL. LEGOK KOLE NO. 54, KP. CIPUTIH 
 KOPERASI DESA MERAH PUTIH CILEUNYI WETAN 	 Jalan Raya Cileunyi Kampung Babakan Situ Nomor 445 
 KOPERASI DESA MERAH PUTIH CIWIDEY 	 JALAN OTONG KARDANA NOMOR 1 
 KOPERASI DESA MERAH PUTIH PATENGAN KECAMATAN RANCABALI KABUPATEN BANDUNG 	 JALAN RAYA RANCABALI - CIWIDEY Km.01 NOMOR 83 
 KOPERASI DESA MERAH PUTIH RANCAMANYAR KECAMATAN BALEENDAH KABUPATEN BANDUNG 	 Jalan Rancamanyar nomor 160 
 KOPERASI DESA MERAH PUTIH DESA CIBEET KECAMATAN IBUN KABUPATEN BANDUNG 	 Kampung Cinangka 
 KOPERASI DESA MERAH PUTIH TANGGULUN KECAMATAN IBUN 	 Jalan Balai Desa Nomor 11 
 KOPERASI DESA MERAH PUTIH KARYALAKSANA 	 Jl. Raya Pangguh No. 2205 
 KOPERASI DESA MERAH PUTIH ARJASARI KECAMATAN ARJASARI 	 KAMPUNG BLOK DESA 
 KOPERASI DESA MERAH PUTIH LAKSANA KECAMATAN IBUN 	 Kp. Sangkan 
 KOPERASI DESA MERAH PUTIH LAMPEGAN KECAMATAN IBUN KABUPATEN BANDUNG 	 JALAN OMA ANGGAWISASTRA NOMOR 1 KAMPUNG BABAKAN KOPO 
 KOPERASI DESA MERAH PUTIH NEGLASARI KECAMATAN IBUN KABUPATEN BANDUNG 	 JALAN GALUDRA-SITUSARI 
 KOPERASI DESA MERAH PUTIH CIKAWAO KECAMATAN PACET 	 KAMPUNG CISINDAN 
 KOPERASI DESA MERAH PUTIH DESA BUNINAGARA KECAMATAN KUTAWARINGIN 	 KAMPUNG CIKAHURIPAN NOMOR 112 
 KOPERASI DESA MERAH PUTIH IBUN KECAMATAN IBUN KABUPATEN BANDUNG 	 Jalan Omaanggawisastra 414, Kampung Paseh 
 KOPERASI DESA MERAH PUTIH DUKUH KECAMATAN IBUN 	 Jalan Widara Nomor 157 
 KOPERASI KELURAHAN MERAH PUTIH ANDIR KECEMATAN BALEENDAH KABUPATEN BANDUNG 	 Kampung Bahuan Nomor 01 
 KOPERASI KELURAHAN MERAH PUTIH BALEENDAH KECAMATAN BALEENDAH 	 Jalan Adikusumah Nomor 14 Kelurahan Baleendah 
 KOPERASI KELURAHAN MERAH PUTIH CIBEUNYING KECAMATAN CIMENYAN 	 KAMPUNG BOJONG KACOR 
 KOPERASI DESA MERAH PUTIH CIMENYAN 	 
 KOPERASI KELURAHAN MERAH PUTIH JELEKONG 	 Jalan Laswi Cangkring Nomor 230 
 KOPERASI KELURAHAN MERAH PUTIH MANGGAHANG KECAMATAN BALEENDAH 	 Jalan Raya Laswi Nomor 159 
 KOPERASI KELURAHAN MERAH PUTIH DESA MEKARWANGI 	 KP Bojongmondro 
 KOPERASI KELURAHAN MERAH PUTIH PADASUKA KECAMATAN CIMENYAN 	 Jalan H. Sarkawi No 25 
 KOPERASI KELURAHAN MERAH PUTIH PASAWAHAN KECAMATAN DAYEUHKOLOT 	 JL RAYA DAYEUHKOLOT GG MASJID BABAKAN CISUMINTA 
 KOPERASI KELURAHAN MERAH PUTIH RANCAEKEK KENCANA KECAMATAN RANCAEKEK KABUPATEN BANDUNG 	 Jl. Teratai Raya Blok 12 Bumi Rancaekek Kencana, Kelurahan Rancaekek Kencana, Kecamatan Rancaekek, Kabupaten Bandung 
 KOPERASI DESA MERAH PUTIH SUDI 	 kp. cisero 
 KOPERASI DESA MERAH PUTIH SUKAMANAH KECAMATAN PANGALENGAN 	 
 KOPERASI KELURAHAN MERAH PUTIH SULAIMAN 	 Jalan Hercules IV Nomor 21, Lanud Sulaiman, Kecamatan Margahayu, Kabupaten Bandung, Provinsi Jawa Barat 
 KOPERASI KELURAHAN MERAH PUTIH WARGAMEKAR 	 Jalan Kawungsari-Rancamanuk`;

// Delay helper to avoid rate limit Nominatim
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const seedKDMP2 = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ DB Connected");

    const lines = rawInput.split("\n").filter((l) => l.trim());
    const tasks = [];

    console.log(`Processing ${lines.length} lines...`);

    for (const line of lines) {
      // Split berdasarkan tab, karena user input copy-paste dari excel/tabel
      // Format: NAMA [TAB] ALAMAT
      // Jika tidak ada tab, coba split manual di spasi panjang jika ada, atau anggap alamat kosong

      let [nama, alamat] = line.split("\t").map((s) => s.trim());

      // Jika split tab gagal, mungkin dipisah spasi ganda?
      if (!alamat && line.includes("   ")) {
        const parts = line.split("   ");
        nama = parts[0].trim();
        alamat = parts.slice(1).join(" ").trim();
      }

      if (!nama) continue;

      // Default jika alamat kosong
      if (!alamat) alamat = "Alamat belum tersedia";

      // Tambahkan "Bandung" agar geocoding lebih akurat
      const queryAddress = `${alamat}, ${nama}, Kabupaten Bandung, Jawa Barat`;

      console.log(`Geocoding: ${nama}...`);
      let coords = await geocodeAddress(queryAddress);

      // Jika gagal, coba geocode nama koperasinya saja + kab bandung
      if (!coords) {
        console.log("  -> Retrying with name only...");
        coords = await geocodeAddress(`${nama}, Kabupaten Bandung`);
      }

      // Jika masih gagal, coba alamatnya saja
      if (!coords) {
        console.log("  -> Retrying with address only...");
        coords = await geocodeAddress(`${alamat}, Kabupaten Bandung`);
      }

      // Default ke pusat Kab Bandung jika gagal total
      let lat = -7.025253;
      let lon = 107.51976;

      if (coords) {
        lat = coords[0];
        lon = coords[1];
        console.log(`  -> Found: ${lat}, ${lon}`);
      } else {
        console.log("  -> ❌ Not found, using default center.");
      }

      tasks.push({
        title: "KDMP",
        description: "VISIT " + nama,
        location: alamat,
        reward: 10000,
        status: "pending",
        segment: "KDMP",
        latitude: lat,
        longitude: lon,
      });

      // Delay 1 detik per request agar tidak kena rate limit
      await delay(1000);
    }

    console.log(`Insert ${tasks.length} tasks...`);
    await Task.insertMany(tasks);
    console.log("✅ Success insert KDMP part 2!");

    process.exit(0);
  } catch (err) {
    console.error("❌ Error:", err);
    process.exit(1);
  }
};

seedKDMP2();
